admin_login_info:
  admin_page_url: "https://www.saucedemo.com/"
  username: "standard_user"
  password: "secret_sauce"
  invalid_username: "invalid_username"
  locked_username: "locked_out_user"
  problem_username: "problem_user"
  performance_glitch_username: "performance_glitch_user"
  error_username: "error_user"
  visual_username: "visual_user"